<?php

#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Thursday 16th of May 2013 06:21:37 PM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------
//http://localhost/test/test2/socialconnect/hybridauth-2.1.2/
return
        array(
            "base_url" => Yii::app()->request->hostInfo . Yii::app()->baseUrl . "/index.php/site/testHybrid",
            "providers" => array(
                "Google" => array(
                    "enabled" => true,
                    "keys" => array("id" => Yii::app()->params['google_key'], "secret" => Yii::app()->params['google_secret'])
                ),
                "Facebook" => array(
                    "enabled" => true,
                    "keys" => array("id" => Yii::app()->params['fb_key'], "secret" => Yii::app()->params['fb_secret'])
                ),
                "Twitter" => array(
                    "enabled" => true,
                    "keys" => array("key" => Yii::app()->params['twitter_key'], "secret" => Yii::app()->params['twitter_secret'])
                ),
                "LinkedIn" => array(
                    "enabled" => true,
                    "keys" => array("key" => Yii::app()->params['linkedin_key'], "secret" => Yii::app()->params['linkedin_secret'])
                ),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => ""
);
