<?php

#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Thursday 16th of May 2013 06:21:37 PM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
 * (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
        array(
            "base_url" => "http://localhost/test/test2/socialconnect/hybridauth-2.1.2/hybridauth/",
            "providers" => array(
                // openid providers
                "OpenID" => array(
                    "enabled" => true
                ),
                "AOL" => array(
                    "enabled" => true
                ),
                "Yahoo" => array(
                    "enabled" => true,
                    "keys" => array(
                        "id" => "",
                        "secret" => ""
                    )
                ),
                "Google" => array(
                    "enabled" => true,
                    "keys" => array("id" => "284978357583.apps.googleusercontent.com",
                        "secret" => "1iN-G15Wy0sfhR0rNONO-wqV")
                ),
                "Facebook" => array(
                    "enabled" => true,
                    "keys" => array("id" => "522175311153131", "secret" => "1e2856455b9a218e27e204e1519a8d3d")
                ),
                "Twitter" => array(
                    "enabled" => true,
                    "keys" => array(
                        
                        "key" => "4qePikLbny5D5VS4GGHHUg", 
                        "secret" => "eYKHpptp9zCDEXPLZAjEw8dQcpjFoL8JfXXh7bxEneA")
                ),
                // windows live
                "Live" => array(
                    "enabled" => true,
                    "keys" => array("id" => "", "secret" => "")
                ),
                "MySpace" => array(
                    "enabled" => true,
                    "keys" => array("key" => "", "secret" => "")
                ),
                "LinkedIn" => array(
                    "enabled" => true,
                    "keys" => array("key" => "x196m9043lsl", "secret" => "4JNFh3VSuNTFAS8j")
                ),
                "Foursquare" => array(
                    "enabled" => true,
                    "keys" => array("id" => "", "secret" => "")
                ),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => ""
);
