<?php

#AUTOGENERATED BY HYBRIDAUTH 2.0.11 INSTALLER - Sunday 20th of May 2012 02:18:23 PM

/* !
 * HybridAuth
 * http://hybridauth.sourceforge.net | https://github.com/hybridauth/hybridauth
 *  (c) 2009-2011 HybridAuth authors | hybridauth.sourceforge.net/licenses.html
 */

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
        array(
            "base_url" => "http://darussalam.ilsainteractive.com/hybridauth/",
            "providers" => array(
                // openid providers
                "OpenID" => array(
                    "enabled" => true
                ),
                "Yahoo" => array(
                    "enabled" => true
                ),
                "AOL" => array(
                    "enabled" => true
                ),
                "Google" => array(
                    "enabled" => true,
                    "keys" => array("id" => "561516674806.apps.googleusercontent.com", "secret" => "6IltULRULS7DQSgBpMi05LOD"),
                    "scope" => ""
                ),
                "Facebook" => array(
                    "enabled" => true,
                    "keys" => array("id" => "441631942586140", "secret" => "0593fcad5651add77a4d531e56476349"),
                    // A comma-separated list of permissions you want to request from the user. See the Facebook docs for a full list of available permissions: http://developers.facebook.com/docs/reference/api/permissions.
                    "scope" => "",
                    // The display context to show the authentication page. Options are: page, popup, iframe, touch and wap. Read the Facebook docs for more details: http://developers.facebook.com/docs/reference/dialogs#display. Default: page
                    "display" => "page"
                ),
                "Twitter" => array(
                    "enabled" => true,
                    "keys" => array("key" => "YsCF0GCKecKfiGhOgZibQ", "secret" => "oBmRCRmqqzFgdw63PwLMwjg9z1wRGoP90V9tWtieQ")
                ),
                // windows live
                "Live" => array(
                    "enabled" => false,
                    "keys" => array("id" => "", "secret" => "")
                ),
                "MySpace" => array(
                    "enabled" => false,
                    "keys" => array("key" => "", "secret" => "")
                ),
                "LinkedIn" => array(
                        "enabled" => true,
                        "keys" => array("key" => "n8ahle5m4q6h", "secret" => "Ss2iigpBpYyvsg0A")
                ),
                "Foursquare" => array(
                    "enabled" => false,
                    "keys" => array("id" => "", "secret" => "")
                ),
            ),
            // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
            "debug_mode" => false,
            "debug_file" => "",
);
